spring:
  cache:
    type: redis
    redis:
      time-to-live: PT60M
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/offers
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:63792}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
joboffers:
  offer-fetcher:
    http:
      scheduler:
        fetchingFrequency: PT3H
      client:
        config:
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
          port: 5057
          connectionTimeout: 5000
          readTimeout: 5000

scheduler:
  enabled: true

jwt:
  auth:
    expirationDays: 30
    secretKey: ${JWT_SECRET_KEY}
    issuer: job-offers-backend-service

server:
  port: 8080